trt

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,7 @@ on:
       - "release/*"
   pull_request:
     types: [opened, synchronize, reopened]
+
 jobs:
   determine_docker_org_and_tag:
     runs-on: ubuntu-latest
@@ -22,10 +23,9 @@ jobs:
       run:
         shell: bash
         working-directory: "/opt/carma/"
-    # Specify the runner environment
     runs-on: ubuntu-latest
     container:
-      image: ${{ needs.determine_docker_org_and_tag.outputs.docker_organization }}/carma-base:develop-humble
+      image: usdotfhwastoldev/carma-base:develop-humble
       env:
         INIT_ENV: "/home/carma/.base-image/init-env.sh"
         ROS_2_ENV: "/opt/ros/humble/setup.bash"
@@ -39,6 +39,12 @@ jobs:
         path: src/${{ github.event.repository.name }}
     - name: Move source code
       run: mv $GITHUB_WORKSPACE/src /opt/carma/
+    - name: Verify ROS Humble Setup File
+      run: |
+        if [ ! -f /opt/ros/humble/setup.bash ]; then
+          echo "ERROR: ROS Humble setup.bash not found!"
+          exit 1
+        fi
     - name: Determine base branch
       id: determine-base-branch
       run: |
